export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    description:
      "Over-ear wireless headphones with noise cancellation and 30-hour battery life.",
    rating: 4.7,
    price: 89.99,
    image: "https://picsum.photos/seed/product1/400/300",
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    description:
      "Track heart rate, sleep, steps, and workouts with a sleek design.",
    rating: 4.5,
    price: 129.99,
    image: "https://picsum.photos/seed/product2/400/300",
  },
  {
    id: 3,
    name: "Mechanical Gaming Keyboard",
    description:
      "RGB backlit keyboard with blue switches and programmable keys.",
    rating: 4.8,
    price: 74.99,
    image: "https://picsum.photos/seed/product3/400/300",
  },
  {
    id: 4,
    name: "Portable SSD 1TB",
    description: "High-speed external SSD with USB-C connectivity.",
    rating: 4.9,
    price: 109.99,
    image: "https://picsum.photos/seed/product4/400/300",
  },
  {
    id: 5,
    name: "4K Webcam",
    description: "Ultra HD webcam with auto-focus and built-in microphone.",
    rating: 4.4,
    price: 59.99,
    image: "https://picsum.photos/seed/product5/400/300",
  },
  {
    id: 6,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI settings.",
    rating: 4.3,
    price: 24.99,
    image: "https://picsum.photos/seed/product6/400/300",
  },
  {
    id: 7,
    name: "Laptop Stand",
    description: "Adjustable aluminum stand for laptops up to 17 inches.",
    rating: 4.6,
    price: 34.99,
    image: "https://picsum.photos/seed/product7/400/300",
  },
  {
    id: 8,
    name: "Smartphone Gimbal",
    description: "3-axis stabilizer for smooth video recording.",
    rating: 4.5,
    price: 99.99,
    image: "https://picsum.photos/seed/product8/400/300",
  },
  {
    id: 9,
    name: "Bluetooth Speaker",
    description:
      "Portable waterproof speaker with deep bass and long battery life.",
    rating: 4.7,
    price: 49.99,
    image: "https://picsum.photos/seed/product9/400/300",
  },
  {
    id: 10,
    name: "USB-C Hub",
    description:
      "Multi-port hub with HDMI, USB 3.0, SD card reader, and PD charging.",
    rating: 4.4,
    price: 39.99,
    image: "https://picsum.photos/seed/product10/400/300",
  },
  {
    id: 11,
    name: "Gaming Chair",
    description:
      "Ergonomic gaming chair with lumbar support and reclining backrest.",
    rating: 4.6,
    price: 199.99,
    image: "https://picsum.photos/seed/product11/400/300",
  },
  {
    id: 12,
    name: "Action Camera",
    description: "Waterproof action camera with 4K recording capabilities.",
    rating: 4.5,
    price: 149.99,
    image: "https://picsum.photos/seed/product12/400/300",
  },
  {
    id: 13,
    name: "Wireless Earbuds",
    description: "Compact earbuds with active noise cancellation.",
    rating: 4.7,
    price: 79.99,
    image: "https://picsum.photos/seed/product13/400/300",
  },
  {
    id: 14,
    name: "Smart Home Camera",
    description:
      "Indoor security camera with motion detection and night vision.",
    rating: 4.4,
    price: 69.99,
    image: "https://picsum.photos/seed/product14/400/300",
  },
  {
    id: 15,
    name: "Electric Kettle",
    description: "1.7L stainless steel kettle with automatic shutoff.",
    rating: 4.3,
    price: 29.99,
    image: "https://picsum.photos/seed/product15/400/300",
  },
  {
    id: 16,
    name: "Air Purifier",
    description: "HEPA filter air purifier suitable for medium-sized rooms.",
    rating: 4.8,
    price: 159.99,
    image: "https://picsum.photos/seed/product16/400/300",
  },
  {
    id: 17,
    name: "Robot Vacuum Cleaner",
    description: "Automatic vacuum cleaner with app control and scheduling.",
    rating: 4.6,
    price: 249.99,
    image: "https://picsum.photos/seed/product17/400/300",
  },
  {
    id: 18,
    name: "LED Desk Lamp",
    description: "Dimmable LED lamp with touch controls and USB charging port.",
    rating: 4.5,
    price: 27.99,
    image: "https://picsum.photos/seed/product18/400/300",
  },
  {
    id: 19,
    name: "Coffee Maker",
    description: "Programmable coffee machine with 12-cup capacity.",
    rating: 4.4,
    price: 79.99,
    image: "https://picsum.photos/seed/product19/400/300",
  },
  {
    id: 20,
    name: "Portable Power Bank",
    description: "20,000mAh power bank with fast charging support.",
    rating: 4.7,
    price: 44.99,
    image: "https://picsum.photos/seed/product20/400/300",
  },
];